# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
ingress:
  enabled: false
nameOverride: "spring-boot-jib"
fullnameOverride: "spring-boot-jib"

service:
  type: NodePort
  port: 30001
  containerPort: 5500

container:
  ports:
    - name: http
      containerPort: 5500
      protocol: TCP
    - name: debug
      containerPort: 5005
      protocol: TCP

securityContext:
  privileged: true
  runAsUser: 0
  runAsNonRoot: false